# Generated by Django 5.2.1 on 2025-06-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_mediopago"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Gasto",
            new_name="Gastos",
        ),
    ]
