# Generated by Django 5.2.1 on 2025-06-04 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_gasto_delete_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mediopago'),
        ),
    ]
